version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        name: Install deps
        command: yarn
    - run:
        name: Build frontend client
        command: yarn build
workflows:
  version: 2
  workflow:
    jobs:
    - build